DROP DATABASE IF EXISTS PROJETOFINALCOTI;
CREATE DATABASE IF NOT EXISTS PROJETOFINALCOTI;

USE PROJETOFINALCOTI;

CREATE TABLE USUARIO(
NOME VARCHAR(50) NOT NULL,
LOGIN VARCHAR(35) PRIMARY KEY,
SENHA VARCHAR(50) NOT NULL
);

CREATE TABLE COMPUTADOR(
NOME VARCHAR(10) PRIMARY KEY,
CPU VARCHAR(20) NOT NULL,
RAM INTEGER NOT NULL,
VIDEO VARCHAR(20) NOT NULL,
DRIVEMIDIA VARCHAR(20) NOT NULL,
HD VARCHAR(20) NOT NULL,
PLACAMAE VARCHAR(20) NOT NULL,
MONITOR VARCHAR(20) NOT NULL,
SO VARCHAR(20) NOT NULL
);

CREATE TABLE IMPRESSORA(
NOME VARCHAR(10) PRIMARY KEY,
MARCA VARCHAR(20) NOT NULL,
MODELO VARCHAR(20) NOT NULL,
CONEXAO VARCHAR(4) NOT NULL
);
